name: Deploy React App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build React App
      working-directory: ./frontend
      run: npm run build

    # Add SSH key setup for rsync
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.AWS_HOST }} >> ~/.ssh/known_hosts

    # Transfer build files to EC2
    - name: Transfer build files to EC2
      run: |
        rsync -avz --delete ./frontend/build/ ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_HOST }}:/home/ubuntu/fr/frontend/build/

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          # Update and install dependencies
          sudo apt-get update -y
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt install -y nodejs
          sudo apt install -y npm
          sudo apt install -y nginx

          # Create directory if it doesn't exist
          mkdir -p /home/ubuntu/fr/frontend

          # Stop nginx to avoid any conflicts
          sudo systemctl stop nginx

          # Create the target directory for the build
          sudo mkdir -p /var/www/vhosts/frontend/build

          # Copy the build files from our synced directory to nginx directory
          sudo cp -R /home/ubuntu/fr/frontend/build/* /var/www/vhosts/frontend/build/

          # Configure nginx
          sudo tee /etc/nginx/sites-available/react << EOF
          server {
              listen 80 default_server;
              server_name _;
              root /var/www/vhosts/frontend/build;
              index index.html;
              
              location / {
                  try_files \$uri \$uri/ /index.html;
              }
          }
          EOF

          # Enable the site and remove default
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo ln -sf /etc/nginx/sites-available/react /etc/nginx/sites-enabled/

          # Set proper permissions
          sudo chown -R www-data:www-data /var/www/vhosts/frontend
          sudo chmod -R 755 /var/www/vhosts/frontend

          # Restart nginx
          sudo systemctl restart nginx