name: Deploy React App to AWS

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # Step 3: Navigate to the React App Directory
    - name: Set Working Directory
      run: cd /home/ubuntu/fr/frontend # Update this with the correct path if `package.json` is not in the root

    # Step 4: Install dependencies
    - name: Install Dependencies
      run: npm install

    # Step 5: Build the React App
    - name: Build React App
      run: npm run build

    # Step 6: Deploy to AWS EC2
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          sudo apt-get update -y
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt install -y nodejs
          sudo apt install -y npm
          sudo apt install -y nginx

          rsync -avz --exclude='node_modules' ./ /home/ubuntu/react-app/
          cd /home/ubuntu/react-app/
          npm install
          npm run build
          sudo mkdir -p /var/www/vhosts/frontend/
          sudo cp -R build/ /var/www/vhosts/frontend/

          sudo rm -f /etc/nginx/sites-enabled/default
          echo "server {
              listen 80 default_server;
              server_name _;
              location / {
                  autoindex on;
                  root /var/www/vhosts/frontend/build;
                  try_files \$uri /index.html;
              }
          }" | sudo tee /etc/nginx/sites-available/react
          sudo ln -sf /etc/nginx/sites-available/react /etc/nginx/sites-enabled/
          sudo gpasswd -a www-data ubuntu
          sudo systemctl restart nginx
          sudo service nginx restart
